# Generated by Django 5.2.8 on 2025-11-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('details', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='ateliers/')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='ateliers/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
