# Generated by Django 5.2.8 on 2025-11-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0002_atelier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atelier',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='realisationimage',
            name='realisation',
        ),
        migrations.DeleteModel(
            name='RealisationCategory',
        ),
        migrations.DeleteModel(
            name='Realisation',
        ),
        migrations.DeleteModel(
            name='RealisationImage',
        ),
    ]
