# Generated by Django 5.2.8 on 2025-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0002_add_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='QHSEPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'QHSE Policies',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
