# Generated by Django 5.2.8 on 2025-11-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0004_rename_image_project_main_image_remove_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Realisation Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='realisations/')),
                ('completion_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, help_text='Ex: 3 mois, 6 semaines', max_length=100)),
                ('budget', models.CharField(blank=True, help_text='Ex: 50M FCFA', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='sicmi_app.realisationcategory')),
            ],
            options={
                'ordering': ['-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='RealisationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realisations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sicmi_app.realisation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
