# Generated by Django 5.2.8 on 2025-11-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0005_teammember_bio_teammember_email_teammember_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='phone',
        ),
    ]
