"""Remove services field from Project model

Generated by assistant to remove the ManyToManyField linking projects to services.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0005_realisationcategory_realisation_realisationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='services',
        ),
    ]
