# Generated by Django 5.2.8 on 2025-11-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0006_remove_teammember_bio_remove_teammember_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
