# Generated by Django 5.2.8 on 2025-11-19 16:14

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_migrate_services(apps, schema_editor):
    """Create ServiceCategory objects and migrate existing services"""
    ServiceCategory = apps.get_model('sicmi_app', 'ServiceCategory')
    Service = apps.get_model('sicmi_app', 'Service')
    
    # Mapping from old category codes to new category data
    category_mapping = {
        'construction': {
            'name': 'Constructions neuves et revamping',
            'slug': 'construction',
            'icon': 'fa-building',
            'description': 'Construction de structures métalliques, bâtiments industriels et revamping',
            'order': 1
        },
        'maintenance': {
            'name': 'Maintenance industrielle',
            'slug': 'maintenance',
            'icon': 'fa-tools',
            'description': 'Maintenance préventive et curative des équipements industriels',
            'order': 2
        },
        'accompagnement': {
            'name': 'Accompagnement',
            'slug': 'accompagnement',
            'icon': 'fa-hands-helping',
            'description': 'Accompagnement technique et conseil en ingénierie',
            'order': 3
        },
        'facade': {
            'name': 'Travaux de Façade',
            'slug': 'facade',
            'icon': 'fa-home',
            'description': 'Installation et rénovation de façades et bardages',
            'order': 4
        },
        'renovation': {
            'name': 'Travaux de rénovation',
            'slug': 'renovation',
            'icon': 'fa-paint-roller',
            'description': 'Rénovation et modernisation de structures existantes',
            'order': 5
        },
    }
    
    # Create categories and store them in a dict
    categories_dict = {}
    for slug, cat_data in category_mapping.items():
        category, created = ServiceCategory.objects.get_or_create(
            slug=slug,
            defaults=cat_data
        )
        categories_dict[slug] = category
    
    # Migrate existing services
    for service in Service.objects.all():
        old_category = service.category
        if old_category in categories_dict:
            service.category_new = categories_dict[old_category]
            service.save(update_fields=['category_new'])


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert ForeignKey back to CharField"""
    Service = apps.get_model('sicmi_app', 'Service')
    
    for service in Service.objects.all():
        if hasattr(service, 'category_new') and service.category_new:
            service.category = service.category_new.slug
            service.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0007_delete_servicecategory'),
    ]

    operations = [
        # Step 1: Create ServiceCategory model
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône FontAwesome (ex: fa-building)", max_length=50)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de Service',
                'verbose_name_plural': 'Catégories de Services',
                'ordering': ['order', 'name'],
            },
        ),
        
        # Step 2: Add new ForeignKey field (nullable temporarily)
        migrations.AddField(
            model_name='service',
            name='category_new',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_temp', to='sicmi_app.servicecategory', verbose_name='Catégorie'),
        ),
        
        # Step 3: Migrate data
        migrations.RunPython(create_categories_and_migrate_services, reverse_migration),
        
        # Step 4: Remove old category field
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        
        # Step 5: Rename category_new to category
        migrations.RenameField(
            model_name='service',
            old_name='category_new',
            new_name='category',
        ),
        
        # Step 6: Make category non-nullable
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='sicmi_app.servicecategory', verbose_name='Catégorie'),
        ),
        
        # Step 7: Update Service model options
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category__order', 'order', 'name']},
        ),
    ]

