# Generated by Django 5.2.8 on 2025-11-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0008_migrate_to_servicecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category__name', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie de Service', 'verbose_name_plural': 'Catégories de Services'},
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='slug',
        ),
    ]
