# Generated by Django 5.2.8 on 2025-11-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0009_alter_service_options_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QHSEPolicy',
        ),
    ]
