# Generated by Django 5.2.8 on 2025-11-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0010_remove_qhse_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
