# Generated by Django 5.2.8 on 2025-11-19 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0011_alter_project_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'atelier")),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atelier',
                'verbose_name_plural': 'Ateliers & Équipements',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AtelierImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ateliers/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sicmi_app.atelier', verbose_name='Atelier')),
            ],
            options={
                'verbose_name': "Image d'atelier",
                'verbose_name_plural': "Images d'ateliers",
                'ordering': ['order'],
            },
        ),
    ]
