# Generated by Django 5.2.8 on 2025-11-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0012_atelier_atelierimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelierimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='ateliers/', verbose_name='Image'),
        ),
    ]
