# Generated by Django 5.2.8 on 2025-11-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0013_fix_atelier_image_path_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelierimage',
            name='image',
            field=models.ImageField(upload_to='ateliers/', verbose_name='Image'),
        ),
    ]
