# Generated by Django 5.2.8 on 2025-11-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicmi_app', '0014_alter_atelierimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelierimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='ateliers/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(max_length=500, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='services/gallery/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='team/'),
        ),
    ]
